---
- name: Download Packer from Packer.IO (Fedora)
  get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: "{{ download_dir }}/packer_{{ packer_version }}_linux_amd64.zip"

- name: Download Vagrant from VagrantUP (Fedora)
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"
    dest: "{{ download_dir }}/vagrant_{{ vagrant_version }}_linux_amd64.zip"

- name: Download Terraform from Terraform.IO (Fedora)
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ download_dir }}/terraform_{{ terraform_version }}_linux_amd64.zip"

- name: Download Vault from VaultProject.IO (Fedora)
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "{{ download_dir }}/vault_{{ vault_version }}_linux_amd64.zip"

- name: Unpack Packer.IO (Fedora)
  unarchive: 
    src: "{{ download_dir }}/packer_{{ packer_version }}_linux_amd64.zip" 
    dest: "/usr/bin/"
  become: yes

- name: Unpack Vagrant (Fedora)
  unarchive: 
    src: "{{ download_dir }}/vagrant_{{ vagrant_version }}_linux_amd64.zip" 
    dest: "/usr/bin/"
  become: yes

- name: Unpack Terraform (Fedora)
  unarchive: 
    src: "{{ download_dir }}/terraform_{{ terraform_version }}_linux_amd64.zip" 
    dest: "/usr/bin/"
  become: yes

- name: Unpack Vault.IO (Fedora)
  unarchive: 
    src: "{{ download_dir }}/vault_{{ vault_version }}_linux_amd64.zip" 
    dest: "/usr/bin/"
  become: yes 

- name: Install Flatpaks (Fedora)
  flatpak:
    name: "{{ item }}"
    state: present
  become: yes
  loop: "{{ flatpaks }}"

- name: Install dnf-plugins-core (Fedora)
  dnf:
    name: dnf-plugins-core
    state: latest
  become: yes 

- name: Get Virtualbox (Fedora)
  get_url:
    url: "{{ virtualbox_url }}"
    dest: "{{ download_dir }}/VirtualBox_amd64.run"

- name: Set permissions for Installation (Fedora)
  file:
    path: "{{ download_dir }}/VirtualBox_amd64.run"
    mode: u+rwx

- name: Install Virtualbox (Fedora)
  command: "{{ download_dir }}/VirtualBox_amd64.run"
  become: yes
