---
- name: Install Workstation-Tools (Ubuntu 18.04)
  include_tasks: ubuntu1804.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'

- name: Install Workstation-Tools (Ubuntu 20.04)
  include_tasks: ubuntu2004.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20'

- name: Install Workstation-Tools (Fedora)
  include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Install Workstation-Tools (RedHat 7)
  include_tasks: redhat7.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install Workstation-Tools (RedHat 8)
  include_tasks: redhat8.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name: Install Workstation-Tools (CentOS 7)
  include_tasks: centos7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install Workstation-Tools (CentOS 8)
  include_tasks: centos8.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'