---
- hosts: 127.0.0.1
  connection: local
  roles:
     - workstation-tools
  vars: 
     download_dir: /home/{{ username }}/Data/wks_downloads
     packer_version: 1.6.1
     vagrant_version: 2.2.9
     terraform_version: 0.13.0
     vault_version: 1.5.0
